name: gsequencer-9
version: '9.0.4'
summary: Advanced Gtk+ Sequencer
description: |
  GSequencer is intended to be use for music composition. It features
  notation, automation and wave form editor. Supporting LADSPA, DSSI
  and LV2 plugins.
icon: snap/local/ags.png

base: core24
grade: stable
confinement: strict

parts:
  gsequencer-9:
    source: https://download-mirror.savannah.gnu.org/releases/gsequencer/9.0.x/gsequencer-9.0.4.tar.gz # See 'snapcraft plugins'
    plugin: autotools
    build-packages: [wget,fop,libinstpatch-dev,libsndfile-dev,libsamplerate-dev,ladspa-sdk,dssi-dev,lv2-dev,libfftw3-dev,libasound2-dev,libjack-jackd2-dev,uuid-dev,libcunit1-dev,docbook-xsl,docbook-xml,gtk-doc-tools,xsltproc]
    stage-packages: [libinstpatch-1.0-2,libfftw3-double3,libfftw3-single3,libsndfile1,libsamplerate0,cmt,xsynth-dssi,calf-plugins,invada-studio-plugins-lv2,swh-plugins,mda-lv2,hydrogen-drumkits,fluid-soundfont-gm,fluid-soundfont-gs]
    override-build: |
      ./configure --prefix=/snap --enable-public-libgsequencer --enable-snap-sandbox --with-poppler --with-gtk-unix-print --disable-introspection
      make -j $SNAPCRAFT_PARALLEL_BUILD_COUNT
      make -j1 pdf
      DESTDIR=$CRAFT_PART_INSTALL make -j1 install
      DESTDIR=$CRAFT_PART_INSTALL make -j1 install-pdf-mkdir
      DESTDIR=$CRAFT_PART_INSTALL make -j1 install-pdf
      rm -rf $CRAFT_PART_INSTALL/snap/include
      mkdir -p $CRAFT_PART_INSTALL/snap/share/applications/
      install -c -p -m 644 gsequencer.desktop $CRAFT_PART_INSTALL/snap/share/applications/gsequencer.desktop
    override-pull: |
      snapcraftctl pull
      autoreconf -fi
    prime:
      - snap/bin/gsequencer
      - snap/bin/midi2xml
      - snap/lib/libags*
      - snap/lib/libgsequencer*
      - snap/share/gsequencer/*
      - snap/share/doc/gsequencer/*
      - snap/share/applications/gsequencer.desktop
      - usr/lib/ladspa/*
      - usr/lib/dssi/*
      - usr/lib/lv2/*
      - usr/lib/$CRAFT_ARCH_TRIPLET/calf/*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libFLAC*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libasound*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libasyncns*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libdatrie*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libdecor*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libdeflate*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libfftw3*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libfftw3_omp*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libfftw3_threads*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libfftw3f*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libfftw3f_omp*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libfftw3f_threads*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libfluidsynth*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libgbm*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libgomp*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libgraphite2*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libgsm*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libinstpatch*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libjack*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libjacknet*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libjackserver*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libjbig*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libjpeg*
      - usr/lib/$CRAFT_ARCH_TRIPLET/liblo*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libmp3lame*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libmpg123*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libogg*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libopus*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libpipewire*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libpixman-1*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libpulse-simple*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libpulse*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libsamplerate*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libSDL2-2.0*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libsensors*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libsharpyuv*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libsndfile*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libthai*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libtiff*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libvorbis*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libvorbisenc*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libwayland-client*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libwayland-cursor*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libwayland-egl*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libwebp*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libwebrtc_audio_processing*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libxml2*
      - usr/lib/$CRAFT_ARCH_TRIPLET/pulseaudio
      - usr/lib/$CRAFT_ARCH_TRIPLET/pulseaudio/libpulsecommon*
      - usr/share/applications/*
      - -etc/X11/*
      - -etc/fonts/*
      - -etc/gtk-2.0/*
      - -etc/init.d/*
      - -usr/share/lintian/*
      - -usr/share/man/*
      - -usr/share/themes/*
      - -usr/share/icons/*
      - -usr/share/fonts/*
      - -usr/share/fontconfig/*
      - -usr/share/doc/*
      - -usr/share/calf/*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/avahi/*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/gbm/*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/gdk-pixbuf-2.0/*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/gtk-2.0/*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libatk*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libLLVM*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libLerc*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libX11-xcb*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libX11*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libXau*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libXcomposite*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libXcursor*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libXdamage*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libXdmcp*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libXext*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libXfixes*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libXi*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libXinerama*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libXrandr*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libXrender*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libXss*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libatk-1.0*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libavahi-client*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libavahi-common*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libcairo*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libcups*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libdrm_amdgpu*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libfontconfig*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libfribidi*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libgallium*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libgdk-x11-2.0*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libgdk_pixbuf-2.0*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libgtk-x11-2.0*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libgtk2.0-0t64/*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libharfbuzz*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libicudata*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libicui18n*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libicuio*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libicutest*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libicutu*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libicuuc*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libpango-1.0*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libpangocairo-1.0*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libpangoft2-1.0*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libxcb-dri3*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libxcb-present*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libxcb-randr*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libxcb-render*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libxcb-shm*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libxcb-sync*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libxcb-xfixes*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libxcb*
      - -usr/lib/$CRAFT_ARCH_TRIPLET/libxshmfence*
      - -usr/bin/X11
      - -usr/bin/calfjackhost
      - -usr/bin/fc*
      - -usr/bin/gtk-update-icon-cache
      - -usr/bin/update-mime-database
      - -usr/include/*

slots:
  dbus-daemon:
    interface: dbus
    bus: session
    name: org.nongnu.gsequencer.gsequencer

apps:
  gsequencer-9:
    command: snap/bin/gsequencer
    extensions: [gnome]
    desktop: snap/share/applications/gsequencer.desktop
    common-id: org.nongnu.gsequencer.gsequencer
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/snap/lib
      XDG_DATA_DIRS: $SNAP/snap/share:$XDG_DATA_DIRS
      LADSPA_PATH: $SNAP/usr/lib/ladspa
      DSSI_PATH: $SNAP/usr/lib/dssi
      LV2_PATH: $SNAP/usr/lib/lv2
      AGS_SNAP_PATH: $SNAP
      AGS_ANIMATION_FILENAME: $SNAP/snap/share/gsequencer/images/gsequencer-800x450.png
      AGS_LOGO_FILENAME: $SNAP/snap/share/gsequencer/images/ags.png
      AGS_CSS_FILENAME: $SNAP/snap/share/gsequencer/styles/ags.css
      AGS_ONLINE_HELP_PDF_FILENAME: $SNAP/snap/share/doc/gsequencer/pdf/user-manual-a4.pdf
    slots:
      - dbus-daemon
    plugs:
      - x11
      - wayland
      - desktop
      - alsa
      - audio-playback
      - audio-record
      - jack1
      - gsettings
      - home
      - dot-gsequencer
      - openvswitch
      - cups

plugs:
  dot-gsequencer:
    interface: personal-files
    write:
    - $HOME/.gsequencer/ags.conf
    - $HOME/.gsequencer/priority.conf
